### ISSUE TITLE
Can't locate plan ID

### ISSUE THREAD

**Issue by vamundse** [wsspg/wsspg-woocommerce-stripe-subscription-payment-gateway#5]
I just installed it and was adding a product. I have already added the tokens. When I type in the ID of the subscription I would like to use, it says "no such plan: 105".

**Comment by robinbayley** [comment]
Hello vamundse,

Are you seeing anything in your [Stripe logs](https://dashboard.stripe.com/test/logs) regarding this issue ?

**Comment by sandeld** [comment]
If you're using "test" API keys, make sure you have created a "test" plan. Likewise, if you're using live mode, make sure the live mode is activated in Stripe.

**Comment by robinbayley** [comment]
For future reference: Wsspg will not send live mode requests unless SSL is enabled. This includes fetching subscription plan details.
