### ISSUE TITLE
Failed Payment due to Insufficient Funds for a Mixed Cart with Free Trial Period = Multiple Subscription Signups

### ISSUE THREAD

**Issue by TKLaracuente** [wsspg/wsspg-woocommerce-stripe-subscription-payment-gateway#7]
Hello, 

**Setup**
There is a problem when you have a mixed cart that includes a simple product as well as a subscription with a trial period AND the payment method fails due to insufficient funds, or a Radar blocking rule (possibly other cases as well). 

**Expected**
I expect no Stripe subscription to be set up.

**What Happens**
The subscription is created despite the failed payment. Further, the gateway tries (a seemingly random number of times) over and over to process the order, creating several failed charges **and several successful new subscriptions** for the same customer. 

This leaves us with a customer in Stripe who should have no subscription, but actually is subscribed 4-8 times. 

Please advise!

**Comment by robinbayley** [comment]
Hello,

Thank you for raising this issue. A fix has been made and is available as part of version 1.0.6.
